const FETCH_HISTORY = "SHOW_HISTORY";
const DELETE_HISTORY = "DELETE_HISTORY";
const FETCH_ORDERS = "FETCH_ORDERS";

export {
  FETCH_HISTORY,
  DELETE_HISTORY,
  FETCH_ORDERS
};
// export const ACTION_TYPES = [
//   FETCH_HISTORY,
//   DELETE_HISTORY,
//   FETCH_ORDERS
// ];
